### ISSUE TITLE
feat-be: 이메일 발송 기능

### ISSUE THREAD

**Issue by cutehumanS2** [woowacourse-teams/2024-cruru#643]
## 목적
> 지원자에게 이메일을 발송 및 발송 내역 저장 기능을 개발합니다. 

## 작업 세부사항
- [x] Gmail의 SMTP 서버를 사용하기 위한 구글 계정 설정
- [x] 다수의 지원자에게 이메일 발송 API 구현
- [x] 발송 내역(Email) 도메인 추가
- [x] API 문서 작성

## 참고 사항
- **`EmailRequest`의 발송자 필드명(현 clubId)을 추천받습니다.**
- 알림톡과 관심사가 다르다고 생각해 우선 Email 도메인으로 생성하였습니다.
- 이메일을 전송하는 부분은 모킹 처리를 하여, 실제로 발송 내역을 저장하는 로직만 테스트하고 있습니다.
- 로컬 환경에서 이메일 전송 기능을 테스트하고 싶다면, application.yml에서 아래 주석 달린 부분에 계정 정보를 직접 입력하고 Application을 실행하시면 됩니다.
```yaml
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME} # 테스트 시 직접 값 하드코딩 할 것
    password: ${EMAIL_PASSWORD} # 테스트 시 직접 값 하드코딩 할 것
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
```

> 아래의 별표줄 밑에  **요구사항 ID**만 작성해주세요. Prefix 금지!

********************
EMAIL_NOTIFY_01
</details>

closes #643
